version: '3.8'

networks:
  django-network:

services:
  web:
    build:
      context: ./config/python
      dockerfile: Dockerfile.prod
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    volumes:
      - ./src:/usr/src/app
    depends_on:
      - db
    networks:
      - django-network
    container_name: django_prod

  db:
    image: postgres:13.0-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod
    networks: 
      - django-network
    container_name: database_prod
