version: '3.8'

networks: 
  django-network:

services:
  web:
    build: 
      context: ./src
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    container_name: django_container
    depends_on:
      - db
    networks: 
      - django-network

  db:
    image: postgres:13.0-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    env_file: 
      - ./.env
    container_name: database
    networks:
      - django-network


    